### ISSUE TITLE
Oddaja

### ISSUE THREAD

**Issue by mihrot** [EvaErzin/Delnice#3]
Projekt imava končan, problem pa je, da sva popolnoma pozabila, da morava prej oddati v pregled in sva se že zmenila za zagovor s profesorjem, jutri.

**Comment by jaanos** [comment]
S popravkom #4 se še vedno ne morem prijaviti v aplikacijo - problem je v tem, da uporabnik `javnost` nima pravice uporabe števcev. To lahko odpravita s sledečim ukazom:
```SQL
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO javnost;
```

**Comment by EvaErzin** [comment]
Popravljeno

**Comment by jaanos** [comment]
Sem odprl še pull request #5 - vseeno pa bosta morala za delovanje aplikacije dati več pravic uporabniku `javnost` na tabeli `django_session` (vsaj brisanje, najbrž pa lahko kar vse pravice). Svetujem, da poskusita aplikacijo zaganjati z javno prijavo, da ujameta morebitne druge napake zaradi nezadostnih pravic.

Še nekaj pripomb (kolikor sem uspel videti):
* Poti `/` nimata nastavljene - morda lahko nastavita preusmeritev na `/sl/`, da bo aplikacija takoj dostopna na http://127.0.0.1:8000/.
* Glede na to, da nimata angleščine, bi bilo smiselno izbirnik jezikov skriti.
* Pri registraciji ni nobenega opozorila, če pride do napake (npr. prekratko geslo). Po uspešni registraciji me je preusmerilo na `/`, zaradi česar sem dobil napako (glejta zgoraj) - koristilo bi vsaj kakšno obvestilo o uspešni prijavi.

**Comment by EvaErzin** [comment]
Napake so popravljene. 
Glede angleščine manjka navodilo za compilanje. Pred zagonom je potrebno v konzoli manage.py zagnati ukaz `compilemessages`.

**Comment by jaanos** [comment]
Ali lahko prosim sprejmeta pull request #5? Poleg tega še vedno niso urejene pravice na tabeli `django_session` (glejta zgoraj), tako da se še vedno ne morem prijaviti.

**Comment by EvaErzin** [comment]
Pravice sem poskusila že večkrat nastaviti, bi bilo lahko narobe še kaj drugega?

**Comment by jaanos** [comment]
Trenutno ima `javnost` le pravici `SELECT` in `INSERT`, napaka pa se zgodi, ker poskuša Django brisati iz tabele. Najbolje bo, če se nastavijo kar vse pravice:
```SQL
GRANT ALL ON django_session TO javnost;
```

**Comment by EvaErzin** [comment]
Zdaj dela?

**Comment by jaanos** [comment]
Zdaj je šlo naprej, ampak očitno bo isto treba narediti še za tabelo `auth_user` (ali morda kar vse tabele, ki se začnejo z `auth_` in `django_`).

**Comment by jaanos** [comment]
Glede na to, da so druge tabele prazne, bi morda res zadostovalo za `auth_user`.

**Comment by EvaErzin** [comment]
Spremenjene pravice na vseh tabelah, ki ze začenjajo z auth_ in django_

**Comment by jaanos** [comment]
Zdaj se lahko prijavim, a ko kliknem na *Moj Portfolio*, me vrže nazaj na prijavo - problem je tukaj:
https://github.com/EvaErzin/Delnice/blob/a11140f07f542bd281a4c950217aeb04fc5a8d2a/DelniceWebApp/views.py#L46-L49
`is_anonymous` je namreč metoda, tako da jo je potrebno klicati, sicer se za `if` obnaša kot `True`.

Tudi po tem popravku dobim
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File ".../DelniceWebApp/views.py", line 75, in portfolio
    for simbol, barva in zip(simboli, pal[::256//len(simboli)]):
ZeroDivisionError: integer division or modulo by zero
```
Problem je očitno, ker še nimam nobenih podatkov, tako da bo potrebno poskrbeti tudi za prikaz takega primera. Svetujem, da si kar naredita novega uporabnika in razmislita, kaj naj bi se prikazalo, ko prvič klikne na *Moj Portfolio*.

**Comment by EvaErzin** [comment]
V dokumentaciji za django je `is_anonymous` atribut (v prejšnjih verzijah metoda, vendar je bila podpora že ukinjena; https://docs.djangoproject.com/en/1.11/ref/contrib/auth/#django.contrib.auth.models.User.is_anonymous). 
Ostalo bi moralo biti zdaj ok.

**Comment by jaanos** [comment]
Sem ravnokar opazil to - vidim, da je že pridružen pull request. Sedaj manjka samo še datoteka `emptyPortf.html` - verjetno si jo pozabila vključiti v commit.

Še ena malenkost: pri odjavi me vrže na Djangovo odjavno stran, tam pa je povezava do administratorskega vmesnika - bolje bi bilo, če do tega ne kaže nobena povezava; pri odjavi bi se pa lahko enostavno zgodila preusmeritev na začetno stran.

**Comment by EvaErzin** [comment]
Težave z odjavo pri meni ni. Vedno me preusmeri na začetno stran. Bi bila lahko tudi tu kakšna razlika zaradi verzije?
Template sem dodala.

**Comment by jaanos** [comment]
V redu, zdaj deluje, tako da bom dodal povezavo na repozitorij predmeta.

Glede odjave pa je v redu, če deluje z novejšo različico Djanga - očitno je tudi tukaj prišlo do sprememb. Tako ni potrebno več nič spreminjati.
